version: '2.3'

volumes:
  postgresvol15:

networks:
  jordan_network:

services:
  postgres:
    image: postgres:14.1-alpine
    networks:
      - jordan_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jordan_rocks
      PGDATA: /pgdata
    volumes:
    - /home/jordanm/Documents/GitHub/OnTrack/postgres/pgconf/postgres.conf:/pgconf
    - postgresvol15:/pgdata
    ports:
      - "5432:5432"