version: '2.3'

volumes:
  postgresvol15:

networks:
  carly_network:

services:
  postgres:
    image: postgres:14.1-alpine
    networks:
      - carly_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ONTrack!44
      PGDATA: /pgdata
    volumes:
    - /Users/carly/OneDrive/School/2022-2023/SWE4103/SWE4103-On-Track/postgres/pgconf:/pgconf
    - postgresvol15:/pgdata
    ports:
      - "5432:5432"