name: CI
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: |
          cd ontrack
          npm install
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
          npm install jest
      - name: setup database
        run: |
          cd backend
          node setup_postgres.js
      - name: Run tests
        run: |
          cd backend
          npm test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
