name: CI
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.1-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: |
          cd ontrack
          npm install
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run migrations
        run: psql -f db/migrations/file_name.sql postgresql://postgres:postgres@localhost:5432/postgres
      - name: Run tests
        run: |
          cd backend
          npm test
      - env: 
          DATABASE_DSN: "user=postgres host=localhost password=postgres port=5432 database=public sslmode=disable"
